### ISSUE TITLE
Needs updating for 1.16

### ISSUE THREAD

**Issue by NoobChester** [Draylar/ding#7]
The mod does not work for any 1.16 snapshots, and crashes the game

**Comment by NoobChester** [comment]
The mod stopped working since 1.16 snapshot 20w10a

**Comment by NeRdTheNed** [comment]
I've submitted a pull request (#8) which hopefully fixes the mod in versions after 20w17a!

**Comment by Draylar** [comment]
Closed thanks to NeRdTheNed.
